version: '3'
services:
  cod2-master-serv:
    image: cod2-master-serv
    build: .
    container_name: cod2-master-serv
    restart: unless-stopped
    tty: true
    ports:
      - 20700:20700
      - 20710:20710
